# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSKoanba' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire'
    	pod 'SDWebImage'
	pod 'SnapKit', '~> 5.0.0'
  pod 'NVActivityIndicatorView'

  # Pods for iOSKoanba

  target 'iOSKoanbaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSKoanbaUITests' do
    # Pods for testing
  end

end
